version: 2
jobs:
  build:
    docker:
      - image: golang:1.11

    working_directory: /go/src/github.com/orlando1409/serverless-ci-cd-pipeline

    environment:
        S3_BUCKET: circleci-lambda-demo

    steps:
      - checkout

      - run:
         name: Install AWS CLI & Zip
         command: |
          apt-get update
          apt-get install -y zip python-pip python-dev
          apt-get
          pip install awscli
          go get -u github.com/aws/aws-lambda-go/events

      - run:
         name: Build
         command: |
          GOOS=linux go build -o main main.go
          zip $CIRCLE_SHA1.zip main
      
      - run:
          name: Push
          command: aws s3 cp $CIRCLE_SHA1.zip s3://$S3_BUCKET

      - run:
          name: Deploy
          command: |
            aws lambda update-function-code --function-name FindAllMovies \
                --s3-bucket $S3_BUCKET \
                --s3-key $CIRCLE_SHA1.zip --region us-east-1